### PR TITLE
Nonrecursive get_req_external.

### PR DESCRIPTION
**Pull request by anntzer**
The recursive implementation of get_req_external would fail when two
libraries are linked against each each other, e.g. libfreetype.so.6 and
libharfbuzz.so.0 on Arch Linux.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
LGTM

**Comment by rmcgibbo** [comment]
LGTM

**Comment by anntzer** [comment]
Any chance for a release some time soon?  Thanks.

**Comment by ehashman** [comment]
I'll cut one later today @anntzer!

**Comment by ehashman** [comment]
Release done and uploaded to PyPI. Let me know if there are any issues. https://github.com/pypa/auditwheel/releases/tag/1.8

**Comment by njsmith** [comment]
You might want to rev the docker image too

On Dec 28, 2017 14:18, "Elana Hashman" <notifications@github.com> wrote:

Release done and uploaded to PyPI. Let me know if there are any issues.
https://github.com/pypa/auditwheel/releases/tag/1.8

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pypa/auditwheel/pull/84#issuecomment-354366752>, or mute
the thread

**Pull request merged**
