### PR TITLE
Fix manylinux #60 bug

### PR DESCRIPTION
**Pull request by rmcgibbo**
Fixes https://github.com/pypa/manylinux/issues/60

### CODE REVIEW

**Comment by rmcgibbo** [comment]
If anyone could figure out how to add a test for https://github.com/pypa/manylinux/issues/60 to the travis test suite here, that would be excellent. I could copy the un-repaired wheel into the test data suite, but we'd still have to download the system-libraries-to-be-grafted-in as well.

**Comment by ogrisel** [comment]
travis failed: elftree is undefined in some cases.

**Comment by ogrisel** [comment]
For the integration tests, I think we should write a bash script that would download and install libhfd5 from the source tarball into the manylinux1 container.

**Comment by njsmith** [comment]
> If anyone could figure out how to add a test

I don't have the time today to grok what the underlying issue actually is, but I've had good luck in the past with writing my own tiny tiny .so's to exercise weird linker issues -- like you can generate a set of .so's with a funky transitive dependency with just this much writing:
```
-- a.c --
extern int from_b();
extern int from_c();
int from_a() {
    return from_b() + from_c();
}

-- b.c --
extern int from_c();
int from_b() {
    return 2 * from_c();
}

-- c.c --
int from_c() {
    return 1;
}

-- build.sh --
gcc c.c -o c.so -shared
gcc b.c -o b.so -shared -L. -lc
# a.so links directly to b.so but not to c.so
gcc a.c -o a.so -shared -L. -lb
```

**Comment by ehashman** [comment]
I *think* I included this fix in #110 but with a little more rigour and some additional tests so I'm going to close this.

**Pull request closed without merging**
