### PR TITLE
Append to RPATH (instead of overwrite)

### LINKED ISSUE #137: RPATH is being incorrectly overwritten
As originally reported by @thomaslima:

Our wheel has a complicated dependency structure. But the gist of it is the following:

dbcore.so (py_ext) -> lib_tl.so (non-py_ext) -> libcurl.so (external library to be grafted)

dbcore already had an `RPATH` set to `$ORIGIN`. So because of its dependency to libcurl.so, `patchelf_set_rpath` *replaced* it to `$ORIGIN/.libs` in `repair.py`, even though it was not necessary. This way, it could no longer find `lib_tl.so`.

See also #134.

### PR DESCRIPTION
**Pull request by thomaslima**
Closes #137 

Test cases in #134 

Not-implemented caveat: https://github.com/pypa/auditwheel/pull/134#issuecomment-457257003

### CODE REVIEW

**Comment by ferdonline** [comment]
Hi @thomaslima 
Any update on this PR? In our project we also depend on internal libraries and require the previous RPATH to be respected.
Independently I arrived to a very similar solution.
```
    prev_rpath = check_output(['patchelf', '--print-rpath', fn]).decode().rstrip('\n\t /')
    check_call(['patchelf', '--remove-rpath', fn])
    if prev_rpath and prev_rpath != rpath:
        rpath += ":" + prev_rpath
```
Feel free to use it.
In this PR, however, it seems the tests fail for some unrelated reason.
We would be happy to help this getting  fixed. Thanks!

**Comment by thomaslima** [comment]
@ferdonline I'd really like some help. I have absolutely no time to look into this at the moment =(

**Comment by fbrennen** [comment]
Hi @thomaslima -- I had a quick go at updating your PR here: https://github.com/pypa/auditwheel/pull/245

**Comment by lkollar** [comment]
#245 implemented this.

**Pull request closed without merging**
