### PR TITLE
support pyelftools-0.24

### LINKED ISSUE #49: auditwheel incorrectly does not determine if shared object is python extension with pyelftools 0.24
Because since that version symbol and section names are strings in elftools and it mentioned in CHANGES.

Here is commit changed behaviour - https://github.com/eliben/pyelftools/commit/108eaea9e75a8b5a1bef46b8ec6224145ac6668d

### PR DESCRIPTION
**Pull request by daa**
In that version symbol and section names are strings, not bytes, fixes #49.

Also some cosmetic changes - added required test dependencies and fixed typo in error message relating patchelf version.

### CODE REVIEW

**Comment by njsmith** [comment]
Looks good to me. Thanks a lot, and sorry for the slow response. (Question: since obviously we are having trouble keeping up with these things -- it's pretty embarrassing that the manylinux images have just been broken for a while without any response! -- would you be interested in joining the maintainer team?)

@rmcgibbo: This is a pretty critical fix, and I think you're the only one who can roll a new release of auditwheel. Do you have the time to do that, or should we switch the docker image to pulling from auditwheel master?

**Comment by rmcgibbo** [comment]
I'll roll a new release now. Thanks for fixing this, @daa!

**Comment by njsmith** [comment]
@rmcgibbo: Awesome! At some point it might be worth considering adding other people to the pypi permissions for auditwheel in case you want to delegate this in the future.

**Comment by rmcgibbo** [comment]
Yeah, will do.` auditwheel-1.5.0` is on PyPI now.

**Comment by rmcgibbo** [comment]
(@njsmith: I just added you and @ogrisel as maintainers on pypi.)

**Comment by njsmith** [comment]
And here's the PR for the docker image: https://github.com/pypa/manylinux/pull/81

**Comment by ogrisel** [comment]
Merged and updated: https://travis-ci.org/pypa/manylinux/builds/170060635

**Comment by daa** [comment]
Thank you very much for merging and for offer to become part of maintainer team. I'll be glad to help but should note that I don't have very much time to devote to this project. However if it doesn't disturb you I'll gratefully accept your invitation if you decide to do so.

**Pull request merged**
