### PR TITLE
Extract using zipfile preserving permission

### PR DESCRIPTION
**Pull request by kumaraditya303**
Fixes https://github.com/pypa/auditwheel/issues/258

### CODE REVIEW

**Comment by kumaraditya303** [comment]
@mayeut Can you approve running workflows ?

**Review by auvipy — CHANGES_REQUESTED** [review]
can you add test too

**Comment by kumaraditya303** [comment]
> can you add test too

That would require adding a wheel file with permissions, should I add such a wheel file and then test its permission after extract ?

**Comment by kumaraditya303** [comment]
@mayeut If you can add a test on the master branch then I can rebase on it and we can check if this change works as expected as the earlier was working.

**Comment by mayeut** [comment]
@kumaraditya303,

Thanks for the PR.

> If you can add a test on the master branch then I can rebase on it and we can check if this change works as expected as the earlier was working.

I unfortunately won't have time for this in the foreseeable future. If you have time to add the test as @auvipy asked, I think it would be enough for now (or at least it would help doing some more checks based on this new test). 

> That would require adding a wheel file with permissions, should I add such a wheel file and then test its permission after extract ?

Yes, the smaller possible wheel file but covering as much permission bits as possible.

**Pull request closed without merging**
