### PR TITLE
Removed unused imports in different files

### PR DESCRIPTION
**Pull request by atombrella**
It overlaps with #116 but this just removes unused imports.

### CODE REVIEW

**Comment by ehashman** [comment]
Hi @atombrella! These PRs all look totally reasonable, I just want to get some earlier stuff merged before I hit merge on these so I don't create conflicts.

Thanks for your contributions!

**Comment by ehashman** [comment]
Mind fixing the merge conflicts?

**Comment by atombrella** [comment]
@ehashman Done.

**Comment by ehashman** [comment]
Great. I'm going to hold off on this PR until I get manylinux2010 merged as this is highly likely to make that PR unmergeable and I'd rather take these changes second. Thanks!

**Pull request merged**
