### PR TITLE
Ensure Travis fails when tests fail [ignore CI failure]

### LINKED ISSUE #105: Failing tests in Travis have incorrect exit status
See any of the logs here https://travis-ci.org/pypa/auditwheel/builds/442957798

The build says it passed but the log shows 3 failed tests.

### PR DESCRIPTION
**Pull request by ehashman**
This should fix #105.

### CODE REVIEW

**Comment by ehashman** [comment]
Hmm, I want the tests to fail, not error. Guess I'll try something else...

**Comment by ehashman** [comment]
So the current test failure is legitimate thanks to #107. I'm going to try to fix that too, but feel free to merge this PR and I can submit that separately.

**Comment by njsmith** [comment]
I think we should replace the script block by an actual script file, that uses `set -euxo pipefail`.

**Comment by ehashman** [comment]
`-u` complains that `$WHEELHOUSE` is undefined so I left that out.

**Comment by njsmith** [comment]
+1

**Comment by ehashman** [comment]
This should be good to go!

**Comment by safijari** [comment]
bump

**Comment by ehashman** [comment]
I got a +1 so once CI completes for this merge of the new changes I will merge.

**Pull request merged**
