### PR TITLE
Integration test for auditwheel repair

### PR DESCRIPTION
**Pull request by ogrisel**
This uses 2 docker containers, one to build numpy and repair the wheel to make it manylinux1 compatible and the other to quickly check that numpy can be installed and works.

### CODE REVIEW

**Comment by ogrisel** [comment]
Travis is green \o/. Note that I chose not to run the full numpy test suite but just run a simple program that does GEMM (BLAS) and SVD (LAPACK).

**Comment by njsmith** [comment]
This is pretty awesome!

It would be great if you could add a regression test specifically for the gfortran problem, though, since patchelf is a bit of a hairy program, and they just merged my patch without any tests :-). (In fact they have no tests at all for `--replace-needed`.) It seems like it shouldn't be that hard -- you could just run the numpy f2py tests if you're feeling lazy? (It might even be worth running the full numpy test suite -- I'll let Robert make the judgement call there :-).)

I guess there's also a question of whether we want to test this here or in the manylinux docker build itself. Or both...

**Comment by ogrisel** [comment]
We would need to build the master branch of patchelf in the manylinux docker image but this is a pain to build as the autotools of centos:5.11 are too old to run the bootstrap script. We could host our own bootstrapped tarball in the meantime though.

**Comment by ogrisel** [comment]
Alternatively it would be possible to do a bit of sed woodo in the Dockerfile to remove the unsupported autotools construct from the master clone of patchelf.

Anyway I think we can already merge this PR as it is and rebase #24 on top of it to add the patchelf tests.

**Comment by matthew-brett** [comment]
I built a tarball with Nathaniel's patches for the tests last night : http://nipy.bic.berkeley.edu/manylinux/patchelf-0.9njs.tar.gz

**Comment by rmcgibbo** [comment]
Do we want to build a proper python / pip-installable interface to patchelf? It would be straightforward to either provide a python library / API that internally invoked the binary or perhaps a little trickier but still straightforward to modify the code to provide an API that we wrap from cython.

**Comment by ogrisel** [comment]
> Do we want to build a proper python / pip-installable interface to patchelf? It would be straightforward to either provide a python library / API that internally invoked the binary or perhaps a little trickier but still straightforward to modify the code to provide an API that we wrap from cython.

I am not sure it's worth writing a Python library on top of it. The command line interface seems good enough to me.

**Pull request merged**
