### PR TITLE
Use PEP600 policy names

### PR DESCRIPTION
**Pull request by mayeut**
Add legacy aliases for `manylinux_2_5`, `manylinux_2_12` & `manylinux_2_17`
The platform tag passed to `auditwheel repair` `--plat` argument can use either the PEP600 tag or the legacy tag.
The repaired wheel will get both platform tags.

e.g. `auditwheel repair --plat manylinux1_x86_64 foo-5.0-cp38-cp38-linux_x86_64.whl` and `auditwheel repair --plat manylinux_2_5_x86_64 foo-5.0-cp38-cp38-linux_x86_64.whl`  will both produce `foo-5.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl`

Builds on top of #287

### CODE REVIEW

**Comment by mayeut** [comment]
Failure on TravisCI ppc64le is unrelated to the PR.

**Review by lkollar — APPROVED** [review]
Looks good. One thing we should consider is to list the aliases on the `--help` explicitly. Right now this can be a bit confusing:

```
 --plat {linux_x86_64,manylinux_2_5_x86_64,manylinux_2_12_x86_64,manylinux_2_17_x86_64,manylinux_2_24_x86_64,manylinux1_x86_64,manylinux2010_x86_64,manylinux2014_x86_64}
```
Maybe we should list the "old" platform tags separatly as legacy tags.

**Comment by mayeut** [comment]
They should be allowed not to be compatible with existing usage of `auditwheel` and thus displayed in this list. However, it might be good to have them referenced as legacy aliases somewhere.
I tried in the help message for `--plat` but the help formatter mess things up and I'm not keen on going raw formatting for all the help...
```
optional arguments:
  -h, --help            show this help message and exit
  --plat {linux_x86_64,manylinux_2_5_x86_64,manylinux_2_12_x86_64,manylinux_2_17_x86_64,manylinux_2_24_x86_64,manylinux1_x86_64,manylinux2010_x86_64,manylinux2014_x86_64}
                        Desired target platform. (default:
                        "manylinux_2_5_x86_64") Legacy tags are still
                        supported: manylinux_2_5_x86_64: manylinux1_x86_64
                        manylinux_2_12_x86_64: manylinux2010_x86_64
                        manylinux_2_17_x86_64: manylinux2014_x86_64
  -L LIB_SDIR, --lib-sdir LIB_SDIR
```

Maybe adding an epilogue:
```
  --no-update-tags      Do not update the wheel filename tags and WHEEL info
                        to match the repaired platform tag.
  --strip               Strip symbols in the resulting wheel

Legacy tags are still supported and alias the new PEP600 tags.
manylinux1_x86_64 is an alias for manylinux_2_5_x86_64. manylinux2010_x86_64
is an alias for manylinux_2_12_x86_64. manylinux2014_x86_64 is an alias for
manylinux_2_17_x86_64.
```

**Comment by mayeut** [comment]
@lkollar,
Since you approved the changes, I will merge this one to get things going forward but I will open another PR to try to address the one concern you have.

**Pull request merged**
